apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mgmt-sandbox-secret
  namespace: admin
spec:
  encryptedData:
    key:
AgCqVUtaYTIrLzDl7rQDyv0/7Tyan4J8kpmman9B4gyjN4IC+Rh5ccr8Mwlm5CZdirZXLs44WJv3lB+VwhhKSet0+vOR+EJiRRzTJ8W9Q6+K/9hT/eYkrQYczuY4my1pzpnPss8OqjPyCayO0FWajZ2jdNYgPHLMD4C29eNDZkRKt/wVT144QNaHwiaccfCptU4Tfmna2pJ2KC/fyFznTlDprJjy4NWmMBslr3othlEbGPH6LJPs7W6Vddc73GNEAvuCU9Ek3tmwaYW8oJ4XUdMRt1rRcROi5Rc8mWJyl0vGiIIZlGTzNObbAqVDSp2k1RH4LMZJGjzH6/wVlb4PPPHIhCA60nLwD+9diZKB29SH2cb+Zwkgjq5YrQ1N+5MCkB77UPRbJ+AkX2y2D9OsoXkzhO+7slcKVVtPtRfqRdIQ72D9DwN9xol1unyCfepg/BbtGbWU7nCuEtAMEBZbEGf5IyTAkYa9MKrWrpzpUx5wz8VnlJpMfz5A3AkIMVD9bvKCdpGkZR2UHiIcGGdf47f3b++mjfBv5LVPy4kurrX3C1fgEAqpNuUFTMK8EFfv06+8t+SvZSbmhNMcvxSvdT1NDE5Cwzd2f0jhJxr1CoHqvKJ/GYeW32LNHb5Ae34Dycny61zEp8a4y9B9TaB8FMPyR1l3oeqa2+E5eEgssQw/9/5rbh2qIXkDPqazDtUfWuFEtmtgM5rJ/XKjW5jrAhiLsRBj+iLXc263V0oOAZ+5

