---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dwp-sscs-tribunals
  namespace: sscs
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.java: glob:prod-*
spec:
  releaseName: sscs-tribunals
  chart:
    repository: https://hmcts.azurecr.io/helm/v1/repo/
    name: sscs-tribunals
    version: 0.0.1
  values:
    java:
      image: hmcts.azurecr.io/hmcts/sscs-tribunals:prod-c5684303
      ingressHost: dwp-sscs-tribunals.demo.platform.hmcts.net
      environment:
        REFORM_TEAM: sscs
        REFORM_SERVICE_NAME: sscs-tribunals
        REFORM_ENVIRONMENT: demo
      apiGateway:
        s2sKey: "AAAAAAAAAAAAAAAA"
        idamClientSecret: "123456"

      dataStoreApi:
        s2sKey: "AAAAAAAAAAAAAAAA"

      definitionStoreApi:
        s2sKey: "AAAAAAAAAAAAAAAA"
    postgresql:
